Kot/create deskof cards
fjprog101/at18 pull request #108
Opened 2022-09-15 02:36 UTC by sergioale9

2022-09-15 20:11 UTC, J0c4 requested changes
@sergioale9 @AdriOli134 this looks good, please check my comments.

Also, PR #89 from @saraialvarezrosas and @MariaAT18 is approved and ready to merge, you might want to wait for that to be merged and then do a rebase along with the updates I'm requesting for your PR. If you get rebased and updated before #89 is merged, we can go ahead and merge yours, in such case, @saraialvarezrosas will need to do rebase again, if you want, sync by chat how do you want to proceed

2022-09-15 23:42 UTC, sergioale9 commented on src/main/java/jalau/at18/kingoftokyo/DeskCards.java
> +public class DeskCards {
changed the name of class and methods

2022-09-15 23:45 UTC, sergioale9 commented on src/main/java/jalau/at18/kingoftokyo/DeskCards.java
> +    private List<CompleteCard> deskOfCards;
Changed type of object list, from CompleteCard to Card

2022-09-15 23:45 UTC, sergioale9 commented on src/test/java/jalau/at18/kingoftokyo/DeskCardsTest.java
> +
solved

2022-09-16 03:22 UTC, J0c4 requested changes
Updates look good, thanks.

There are conflicts that need to be solved, please try to solve them using git rebase, if you need help, we can check during tomorrow's class

2022-09-16 14:35 UTC, J0c4 approved these changes

2022-09-16 14:49 UTC, merged