Archs/alvaro/create red card class
fjprog101/at18 pull request #92
Opened 2022-09-14 02:11 UTC by junior0123

2022-09-14 17:55 UTC, J0c4 requested changes
Looks good! however, this need to point to main branch, please update it and I'll approve

2022-09-14 19:26 UTC, junior0123 commented
ready, switched to main integration branch

2022-09-14 19:26 UTC, junior0123 commented
> Looks good! however, this need to point to main branch, please update it and I'll approve

ready, switched to main integration branch

2022-09-15 01:50 UTC, J0c4 approved these changes

2022-09-15 13:47 UTC, J0c4 approved these changes

2022-09-15 13:47 UTC, merged